###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

_site_root: /
_site_url: 