title: Standard Page

fields:

  content:
    hide: true

  icon:
    type: text
    display: Font Awesome Icon

  image: 
    type: file
    display: Background Image
    allowed: [png, jpg, gif]
    destination: assets/img/

  call_to_action:
    display: Call To Action
    type: text

  phone_number:
    display: Phone Number
    type: text

  call_to_action_form:
    type: text
    display: Call To Action Above Form

  summary:
    display: Landing Page summary
    type: redactor

  details:
    display: Service Details (optional)
    type: redactor


