###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

_site_root: /~philippe/dwight_the_knight/statamic/
_site_url: ~philippe/dwight_the_knight/statamic/